// @ts-check
// 与 meshtastic 一致：完全自动生成侧边栏，
// 分类的顺序 / 标题 / 折叠行为由各目录下的 _category_.yml 控制。

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  Sidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
